namespace SharpAttributeParser.Recording;

internal interface IArrayConstructorAttributeRecordBuilder : IRecordBuilder<IArrayConstructorAttributeRecord>, ISemanticArrayConstructorAttributeRecordBuilder, ISyntacticArrayConstructorAttributeRecordBuilder { }
