namespace SharpAttributeParser.Recording;

internal interface IArrayConstructorAttributeRecordBuilder : ISemanticArrayConstructorAttributeRecordBuilder, ISyntacticArrayConstructorAttributeRecordBuilder { }
