namespace SharpAttributeParser.Recording;

internal interface ICombinedAttributeRecordBuilder : IRecordBuilder<ICombinedAttributeRecord>, ISemanticCombinedAttributeRecordBuilder, ISyntacticCombinedAttributeRecordBuilder { }
