namespace SharpAttributeParser.Recording;

public interface IGenericAttributeRecordBuilder : IRecordBuilder<IGenericAttributeRecord>, ISemanticGenericAttributeRecordBuilder, ISyntacticGenericAttributeRecordBuilder { }
