namespace SharpAttributeParser.Recording;

internal interface INamedAttributeRecordBuilder : IRecordBuilder<INamedAttributeRecord>, ISemanticNamedAttributeRecordBuilder, ISyntacticNamedAttributeRecordBuilder { }
