namespace SharpAttributeParser.Recording;

internal interface IParamsAttributeRecordBuilder : IRecordBuilder<IParamsAttributeRecord>, ISemanticParamsAttributeRecordBuilder, ISyntacticParamsAttributeRecordBuilder { }
