namespace SharpAttributeParser.Recording;

public interface IQualifiedGenericAttributeRecordBuilder : IRecordBuilder<IQualifiedGenericAttributeRecord>, ISemanticQualifiedGenericAttributeRecordBuilder, ISyntacticQualifiedGenericAttributeRecordBuilder { }
