namespace SharpAttributeParser.Recording;

public interface IQualifiedGenericAttributeRecordBuilder : ISemanticQualifiedGenericAttributeRecordBuilder, ISyntacticQualifiedGenericAttributeRecordBuilder { }
