namespace SharpAttributeParser.Recording;

internal interface ISimpleConstructorAttributeRecordBuilder : IRecordBuilder<ISimpleConstructorAttributeRecord>, ISemanticSimpleConstructorAttributeRecordBuilder, ISyntacticSimpleConstructorAttributeRecordBuilder { }
