namespace SharpAttributeParser.Recording;

internal interface ISimpleConstructorAttributeRecordBuilder : ISemanticSimpleConstructorAttributeRecordBuilder, ISyntacticSimpleConstructorAttributeRecordBuilder { }
