name: Test PR

on:
  pull_request:
    branches:
      - main
      - dev
      
jobs:

  test-pr:
    name: Test PR
    runs-on: ubuntu-latest

    steps:

      - name: Test PR
        uses: SharpAttributeParser/actions/dotnet/nuget/test@v0